server:
  port: 8081
spring:
  main:
    banner-mode: off # 关闭SpringBoot启动图标(banner)
  application:
    name: hmdp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: 192.168.84.200
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mail:
    host: smtp.qq.com
    username: "2843638389@qq.com" #可以改成你的邮箱号，需要开启smtp
    password: "vnwcjxnhrlydddcd"
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true


mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包，这个包下的实体类在做mapper配置时就不需要再写全名了，写类名就行
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false # 关闭mybatisplus启动图标
logging:
  level:
    com.hmdp: debug
